apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: smitstore.smithsonite.home
    path: "/media/smitstore/storage/kubernetes-volumes"