{
 "title": "Cluster",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes) / sum (kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Memory by Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace!=\"\"}[5m])) by(container_label_io_kubernetes_pod_namespace)",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}}"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}) without(instance, job)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Container CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "CPU by Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace!=\"\"}[5m])) by(container_label_io_kubernetes_pod_namespace)",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}}"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"}) without(instance, job)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m]))"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Containers: Running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Containers: Terminated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Containers: Waiting",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}